### ISSUE TITLE
TargetInvocationException

### ISSUE THREAD

**Issue by mgnslndh** [impsnldavid/skiasharpwpfextensions#3]
Nice example of Skia in WPF! It looks good but I suddenly got a TargetInvocationException out of the blue. Got any ideas if this is your wrapper causing it or if it is related to SkiaSharp?
## Inner NullReferenceException Stack Trace

```
   at SkiaSharp.SKObject.RegisterHandle(IntPtr handle, SKObject instance)
   at SkiaSharp.SKCanvas..ctor(IntPtr handle)
```
## TargetInvocationException Stack Trace

```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SkiaSharp.SKObject.GetObject[TSkiaObject](IntPtr handle)
   at SkiaSharp.WpfExtensions.SkiaControl.OnRender(DrawingContext dc) in C:\Users\_\Documents\GitHub\skiasharpwpfextensions\src\Imp.SkiaSharpWpfExtensions\SkiaControl.cs:line 83
   at System.Windows.UIElement.Arrange(Rect finalRect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Imp.SkiaSharpWpfExtensions.Example.App.Main() in C:\Users\magnu_000\Documents\GitHub\skiasharpwpfextensions\src\Imp.SkiaSharpWpfExtensions.Example\obj\x64\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by pixsperdavid** [comment]
I was seeing this occasionally also. I'm fairly sure it's a SkiaSharp bug, but I haven't been able to reliably reproduce it.

**Comment by mgnslndh** [comment]
I investigated it a bit further and there seems to be a piece of code that could fail when a property of the type SKObject is null. I've created an [issue](https://github.com/mono/SkiaSharp/issues/39) and a tiny [pull request](https://github.com/mono/SkiaSharp/pull/40). We'll see how that turns out.

**Comment by mgnslndh** [comment]
Had your program run over night with the fix applied to SkiaSharp. No crash. Hopefully they will release a new nuget soon.

**Comment by pixsperdavid** [comment]
Good to hear! Thanks for clearing this one up

**Comment by mgnslndh** [comment]
It would be nice if your WPF support could be incorporated into SkiaSharp. Or perhaps tidied up and put into its on nuget SkiaSharp.Wpf.

Would you be interested in that? I've asked for an official WPF sample in the SkiaSharp repo but I guess they would rather have somebody else contribute the necessary pieces.
